title: Blog
structure:
  root: false
dated: true
past_date_behavior: public
future_date_behavior: private
sort_dir: desc
blueprint: article
template: article
route: /blog/{slug}
taxonomies:
  - tags
  - categories